/**
 * LFE-PUBLIC-API-01 — Freeze PUBLIC allowlist (root barrel).
 * SSOT tiers: docs/lfe/LFE_ARCHITECTURE_FREEZE.md §3 (+ §3.6A/B).
 * Keep in sync with packages/lfe/src/index.ts exports.
 */
export const LFE_PUBLIC_ALLOWLIST = [
  // §3.2 Status
  'LFE_VERSION',
  'LFE_STATUS',
  'getEngineStatus',
  'EngineStatus',
  'EngineModuleStatus',
  'EngineStatusReport',
  // §3.3 Session
  'createMatch',
  'MatchSession',
  'MatchSessionConfig',
  'SessionStatus',
  'MatchInput',
  'MatchResult',
  'MatchEvent',
  // §3.4 Domain types
  'MatchModel',
  'MatchState',
  'MatchPhase',
  'MatchClock',
  'MatchPeriod',
  'MatchSettings',
  'MatchTeam',
  'MatchPlayer',
  'MatchPlayerAttributes',
  'PlayerSkills',
  'PlayerCondition',
  'Formation',
  'FormationSlot',
  'FormationCode',
  'Lineup',
  'LineupSlot',
  'Bench',
  'Ball',
  'Pitch',
  'Goal',
  'Referee',
  'Weather',
  'Stadium',
  'Score',
  'Substitution',
  'Card',
  'Injury',
  'Statistics',
  'TeamStatistics',
  'PlayerStatistics',
  'PitchSide',
  'PitchRole',
  'PitchPoint',
  'MatchTactics',
  // §3.5 Domain factories (transitional)
  'createPlayer',
  'createTeam',
  'createLineup',
  'createBench',
  'createMatchSettings',
  'formationByCode',
  'FORMATION_442',
  'FORMATION_433',
  'DEFAULT_MATCH_SETTINGS',
  'DEFAULT_PITCH',
  'DEFAULT_PLAYER_ATTRIBUTES',
  'DEFAULT_PLAYER_SKILLS',
  'DEFAULT_PLAYER_CONDITION',
  // §3.6 Commands
  'Command',
  'CommandResult',
  'CommandSource',
  'MatchCommand',
  'MatchCommandType',
  'StartMatchCommand',
  'KickoffCommand',
  'PauseMatchCommand',
  'ResumeMatchCommand',
  'EndMatchCommand',
  'AbandonMatchCommand',
  'DeclareWalkoverCommand',
  'createStartMatchCommand',
  'createKickoffCommand',
  'createPauseMatchCommand',
  'createResumeMatchCommand',
  'createEndMatchCommand',
  'createAbandonMatchCommand',
  'createDeclareWalkoverCommand',
  'TacticalCommand',
  'TacticalCommandType',
  'ChangeTacticsCommand',
  'SubstitutePlayerCommand',
  'SetPressingCommand',
  'SetTempoCommand',
  'SetWidthCommand',
  'SetMentalityCommand',
  'SetPlayerInstructionCommand',
  'ChangeFormationCommand',
  'createChangeTacticsCommand',
  'createSubstitutePlayerCommand',
  'createSetPressingCommand',
  'createSetTempoCommand',
  'createSetWidthCommand',
  'createSetMentalityCommand',
  'createSetPlayerInstructionCommand',
  'createChangeFormationCommand',
  // §3.6A Events (Production MUST)
  'EngineEvent',
  'EngineEventType',
  'GameplayMatchEventType',
  'GAMEPLAY_MATCH_EVENTS',
  // §3.7 Spatial
  'Position',
  'MatchSpatialState',
  'SpatialPlayer',
  'SpatialBall',
  'createMatchSpatialState',
  'findSpatialPlayer',
  // §3.8 Config
  'LfeConfig',
  'DeepPartial',
  'DEFAULT_LFE_CONFIG',
  'LogLevel',
] as const;

export type LfePublicExportName = (typeof LFE_PUBLIC_ALLOWLIST)[number];
